# Generated by Django 4.2.1 on 2023-05-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
